### ISSUE TITLE
重定向的次数过多，网页无法打开

### ISSUE THREAD

**Issue by buildaworld** [yamisenyuki/Deye-Device-Information-Getter#2]
`该网页无法正常运作
deyedev.tat.moe 将您重定向的次数过多。
ERR_TOO_MANY_REDIRECTS`

尝试过mac，windows，iphone平台上的chrome、safari、edge浏览器，均提示相同内容

也尝试过使用[postamn的方式获取](https://xiking.win/2020/11/12/3-deye-dehumidifer-add-to-homeassistant/)，提示 `Miss jwt header` （token获取无问题）

请问还有什么我可以尝试的么？

**Comment by yamisenyuki** [comment]
由于启用了 CDN 并强制跳转了 HTTPS 导致 GitHub 证书过期后无法续签，无限循环HTTP和HTTPS跳转，目前已经修复。

**Comment by buildaworld** [comment]
感谢，已经能正常打开了
